#!/bin/bash

echo "🔧 Bitbucket API Token Setup Helper"
echo "==================================="
echo ""
echo "Follow these steps to get your Bitbucket API Token:"
echo ""
echo "1. Open: https://bitbucket.org/account/settings/api-tokens"
echo "2. Click 'Create API token'"
echo "3. Name it: 'CLI Tool' or 'jira-bitbucket-cli'"
echo "4. Select these scopes:"
echo "   ✅ Pull requests: Read"
echo "   ✅ Repositories: Read"
echo "   ✅ Webhooks: Read and write"
echo "5. Click 'Create'"
echo "6. COPY the generated API token immediately!"
echo ""
echo "❗ IMPORTANT:"
echo "- API tokens are shown only once - save it immediately!"
echo "- This replaces the old app passwords system"
echo "- Use the generated token, not your regular password"
echo ""
echo "Once you have the token, run:"
echo "./devflow config set bitbucket.token YOUR_API_TOKEN"
echo ""
echo "Then test with:"
echo "./devflow bitbucket list-prs --repo autonomy"
echo ""
echo "📝 Note: Bitbucket API tokens use Bearer authentication"